### ISSUE TITLE
How to install this extension

### ISSUE THREAD

**Issue by eArabic** [witsec/mobirise-custom-html#1]
Hello
Thanks a lot, I did not know how to install it.
How to install this extension.
best regards

**Comment by witsec** [comment]
Hi @eArabic, sorry I didn't see this until just now :(.

GitHub only stores the files that Mobirise needs, but you can't import these as they aren't zipped into a .mbrext file. You can download the latest version here: https://witsec.nl/files/witsec-custom-html-v0.1.mbrext.

To install:
In Mobirise, go to "Menu" (top-left), "Extensions" and then click "Import" at the top.

**Comment by witsec** [comment]
I've added a little [README](https://github.com/witsec/mobirise-custom-html) to this repository. This contains a link to my website, where you can find all my Mobirise extensions.
